ansible_user: ec2-user
ansible_password: DevOps321

MONGODB_HOST: mongo-dev.happielearning.com
REDIS_HOST: redis-dev.happielearning.com
USER_HOST: user-dev.happielearning.com
CART_HOST: cart-dev.happielearning.com
CATALOGUE_HOST: catalogue-dev.happielearning.com
MYSQL_HOST: mysql-dev.happielearning.com
SHIPPING_HOST: shipping-dev.happielearning.com
RABBITMQ_HOST: rabbitmq-dev.happielearning.com
PAYMENT_HOST: payment-dev.happielearning.com
FRONTEND_HOST: frontend-dev.happielearning.com