$ANSIBLE_VAULT;1.1;AES256
38363130333434366562366665366664366533653466386633663366376237343362616164326632
3565326532343562303531356464323539313631663961630a613264393063353534643433363431
63333466366539353565326562333833643432633833646464613161373139316631376335333666
3037383231373962390a316234343266633464396266666530313830323766663964313135333330
65313637623134326135653563306637353165316530336263643338666336333336613262623933
3161656330313062656339623737623863393435343631613931