- name: install rabbitmq-server
  ansible.builtin.import_role:
    name: common
    tasks_from: rabbitmq-setup.yaml
- name: copy rabbitmq repo
  ansible.builtin.copy:
    src:  rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: start and enable rabbitmq service
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present