  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.dnf:
      name: "mongodb-org"
  - name: replace localhost to any server
    ansible.builtin.replace:
      path: "/etc/mongod.conf" 
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
  - name: enable and start service
    ansible.builtin.service:
      name: "mongod"
      enabled: true
      state: started