- name: app setup import role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs setup import role
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml
