- name: app setup import role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs setup import role
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: nodejs setup import role
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: "mongodb-mongosh"
    state: present

- name: check if schema exists
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print output 
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load product data
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: start and enable catalogue service
  ansible.builtin.service: 
    name: catalogue
    state: restarted
    enabled: yes