- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - mysql
  - maven

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app