- name: "{{ component }} app-setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: "{{ component }} nodejs setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: copy {{cart}} file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: daemon-reload 
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable cart service
  ansible.builtin.service:
    name: "cart"
    state: restarted
    enabled: yes